# This is a basic workflow to help you get started with Actions

name: ICU4C Android Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Runs a set of commands using the runners shell
      - name: Build Icu4c
        run: |
          wget https://github.com/unicode-org/icu/releases/download/release-77-1/icu4c-77_1-src.tgz && tar -zxf icu4c-77_1-src.tgz
          bash cc-icu4c.sh build --arch=arm --library-type=static --ndk-dir=${ANDROID_NDK} --icu-src-dir=icu --build-dir=./build
      - name: Upload production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: icu4c-android
          path: ./build/install/
